name: geotrivia
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  ########
  go_router: ^3.0.1
  #############
  logging: ^1.0.2
  ######## statemangment // google
  provider: ^6.0.2
  ####### local storage save small data
  shared_preferences: ^2.0.13
  ################ auth

  firebase_auth: ^3.4.1
  fluttertoast:
  firebase_core: ^1.15.0  # Needed for Crashlytics below
  firebase_crashlytics: ^2.8.1  # Error reporting
  games_services: ^2.0.7  # Achievements and leaderboards
  cloud_firestore: ^3.2.1
  geolocator: ^9.0.0
  flag: ^6.0.0
  country_codes: ^2.2.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/geotrivia.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
